
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    username: u
    password: 1
    url: jdbc:h2:file:./data/db
  liquibase:
    url: jdbc:h2:file:./data/db
    user: u
    password: 1
logging:
  level:
    org.springframework: trace
jwt:
  secret: 44vbOhW7I5RCz5O2cIZFrP5Jwm1Ko2XsdvquN1Pi7W2KVIA5EROzX2nuQM33cUThOxV1ZYeigcIbx9caGPS8HdutBtAtApU/W+V7HlI363hC/LFh9kxYn8B6Eq1aHZ2joAzHMZQzKRLB7CWsYhZrmXhP1VfrjcwfY/BoxtKuSBQ=
  expiration-millis: 86400000