server:
  error:
    include-message: always
    include-stacktrace: never
    include-exception: true
spring:
  application:
    name: shoe_shop
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    change-log: db/changelog/master-changelog.xml
    clear-checksums: true
    drop-first: true
application:
  session:
    expiration-millis: 86400000